
services:
  # Backend service (Node.js)
  app:
    image: johnjosephwayne/evaluation_docker/app:latest
#    build:
#      context: ./Backend
#      dockerfile: Backend/backend_dockerfile
    networks:
      - backend
      - proxy
    depends_on:
      - db
    volumes:
      - app_logs:/app/logs

  # Frontend service (Angular + Nginx)
  frontend:
    image: johnjosephwayne/evaluation_docker/frontend:latest
#    build:
#      context: ./Frontend
#      dockerfile: Frontend/frontend_dockerfile
    volumes:
      - nginx_logs:/var/log/nginx
    ports:
      - "3000:80"
    networks:
      - proxy
    depends_on:
      - db

  # Nginx reverse proxy service
  reverse-proxy:
    image: nginx:1.27
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/templates/default.conf.template
    networks:
      - proxy
    depends_on:
      - app
      - frontend

  # MySQL database service
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend

  # PHPMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_eval
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - "8181:80"
    networks:
      - backend
      - proxy

networks:
  backend:
  proxy:

volumes:
  dbdata:
  app_logs:
  nginx_logs:
