services:
  backend:
    build:
      context: .
      dockerfile: ./Backend/backend.Dockerfile
    image: johnjosephwayne/evaluation_docker:backend
    networks:
      - backend
      - proxy
    depends_on:
      - db
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: .
      dockerfile: ./Frontend/frontend.Dockerfile
    image: johnjosephwayne/evaluation_docker:frontend
    networks:
      - proxy
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
  proxy:
